"""initial_schema_baseline

Revision ID: 6ca2983481ac
Revises: 
Create Date: 2026-10-02 19:29:04.733934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca2983481ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('sales_channels', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_reset_token_user_expires', ['user_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_org_action', ['organization_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('calculation_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('settlement_is_net', sa.Boolean(), nullable=True),
    sa.Column('deduct_marketplace_fees', sa.Boolean(), nullable=True),
    sa.Column('include_shipping', sa.Boolean(), nullable=True),
    sa.Column('include_return_cost', sa.Boolean(), nullable=True),
    sa.Column('critical_risk_margin_threshold', sa.Float(), nullable=True),
    sa.Column('warning_risk_return_rate_threshold', sa.Float(), nullable=True),
    sa.Column('warning_risk_rto_rate_threshold', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculation_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculation_configs_organization_id'), ['organization_id'], unique=True)

    op.create_table('organization_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('organization_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('billing_cycle', sa.String(), nullable=True),
    sa.Column('monthly_upload_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_transaction_limit', sa.Integer(), nullable=True),
    sa.Column('max_skus', sa.Integer(), nullable=True),
    sa.Column('uploads_used_this_month', sa.Integer(), nullable=True),
    sa.Column('transactions_used_this_month', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_subscriptions_organization_id'), ['organization_id'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('purchase_cost', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_org_sku_unique', ['organization_id', 'sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)

    op.create_table('sku_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('period_name', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('units_sold', sa.Integer(), nullable=True),
    sa.Column('returned_units', sa.Integer(), nullable=True),
    sa.Column('cancellation_units', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('returns_count', sa.Integer(), nullable=True),
    sa.Column('return_rate', sa.Float(), nullable=True),
    sa.Column('sale_linked_return_rate', sa.Float(), nullable=True),
    sa.Column('rto_count', sa.Integer(), nullable=True),
    sa.Column('rto_rate', sa.Float(), nullable=True),
    sa.Column('total_product_cost', sa.Float(), nullable=True),
    sa.Column('marketplace_fees', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('return_cost', sa.Float(), nullable=True),
    sa.Column('return_value', sa.Float(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('net_settlement', sa.Float(), nullable=True),
    sa.Column('actual_profit', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('profit_leakage', sa.Float(), nullable=True),
    sa.Column('cogs_available', sa.Boolean(), nullable=True),
    sa.Column('settlement_available', sa.Boolean(), nullable=True),
    sa.Column('rto_available', sa.Boolean(), nullable=True),
    sa.Column('data_confidence', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sku_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_org_sku_metric_unique', ['organization_id', 'sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_sku_metrics_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_metrics_sku'), ['sku'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('upload_status', sa.String(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('column_mapping', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_organization_id'), ['organization_id'], unique=False)

    op.create_table('cashback_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('seller_gstin', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_item_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('document_subtype', sa.String(), nullable=True),
    sa.Column('credit_debit_note_id', sa.String(), nullable=True),
    sa.Column('invoice_amount', sa.Float(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('taxable_value', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('tcs', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('customer_delivery_state', sa.String(), nullable=True),
    sa.Column('is_shopsy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashback_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_cb_org_order_item', ['organization_id', 'order_id', 'order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashback_ledger_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashback_ledger_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashback_ledger_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashback_ledger_upload_id'), ['upload_id'], unique=False)

    op.create_table('order_item_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('seller_gstin', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_item_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('fsn', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_subtype', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('fulfilment_type', sa.String(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_approval_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('shipped_from_state', sa.String(), nullable=True),
    sa.Column('warehouse_id', sa.String(), nullable=True),
    sa.Column('price_before_discount', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('seller_share', sa.Float(), nullable=True),
    sa.Column('bank_offer_share', sa.Float(), nullable=True),
    sa.Column('price_after_discount', sa.Float(), nullable=True),
    sa.Column('shipping_charge', sa.Float(), nullable=True),
    sa.Column('invoice_amount', sa.Float(), nullable=True),
    sa.Column('taxable_value', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('tcs', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('buyer_invoice_id', sa.String(), nullable=True),
    sa.Column('buyer_invoice_date', sa.DateTime(), nullable=True),
    sa.Column('buyer_invoice_amount', sa.Float(), nullable=True),
    sa.Column('customer_billing_pincode', sa.String(), nullable=True),
    sa.Column('customer_billing_state', sa.String(), nullable=True),
    sa.Column('customer_delivery_pincode', sa.String(), nullable=True),
    sa.Column('customer_delivery_state', sa.String(), nullable=True),
    sa.Column('usual_price', sa.Float(), nullable=True),
    sa.Column('is_shopsy', sa.Boolean(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_ledger_org_order_item_evt', ['organization_id', 'order_id', 'order_item_id', 'event_subtype'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_ledger_event_subtype'), ['event_subtype'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_ledger_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_ledger_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_ledger_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_ledger_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_ledger_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_ledger_upload_id'), ['upload_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_org_order_date', ['organization_id', 'order_date'], unique=False)
        batch_op.create_index('idx_org_order_sku_unique', ['organization_id', 'order_id', 'sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_upload_id'), ['upload_id'], unique=False)

    op.create_table('returns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('return_reason', sa.String(), nullable=True),
    sa.Column('return_cost', sa.Float(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('is_rto', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index('idx_org_return_order_sku', ['organization_id', 'order_id', 'sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_upload_id'), ['upload_id'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('settlement_amount', sa.Float(), nullable=True),
    sa.Column('marketplace_fee', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('shipping_charge', sa.Float(), nullable=True),
    sa.Column('return_charge', sa.Float(), nullable=True),
    sa.Column('other_charge', sa.Float(), nullable=True),
    sa.Column('settlement_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index('idx_org_settlement_txn_sku', ['organization_id', 'transaction_id', 'sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_upload_id'), ['upload_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_upload_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_sku'))
        batch_op.drop_index(batch_op.f('ix_settlements_organization_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_order_id'))
        batch_op.drop_index('idx_org_settlement_txn_sku')

    op.drop_table('settlements')
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_upload_id'))
        batch_op.drop_index(batch_op.f('ix_returns_sku'))
        batch_op.drop_index(batch_op.f('ix_returns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_returns_order_id'))
        batch_op.drop_index('idx_org_return_order_sku')

    op.drop_table('returns')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_upload_id'))
        batch_op.drop_index(batch_op.f('ix_orders_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_orders_sku'))
        batch_op.drop_index(batch_op.f('ix_orders_organization_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_date'))
        batch_op.drop_index('idx_org_order_sku_unique')
        batch_op.drop_index('idx_org_order_date')

    op.drop_table('orders')
    with op.batch_alter_table('order_item_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_ledger_upload_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_ledger_sku'))
        batch_op.drop_index(batch_op.f('ix_order_item_ledger_organization_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_ledger_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_ledger_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_ledger_order_date'))
        batch_op.drop_index(batch_op.f('ix_order_item_ledger_event_subtype'))
        batch_op.drop_index('idx_ledger_org_order_item_evt')

    op.drop_table('order_item_ledger')
    with op.batch_alter_table('cashback_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashback_ledger_upload_id'))
        batch_op.drop_index(batch_op.f('ix_cashback_ledger_organization_id'))
        batch_op.drop_index(batch_op.f('ix_cashback_ledger_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_cashback_ledger_order_id'))
        batch_op.drop_index('idx_cb_org_order_item')

    op.drop_table('cashback_ledger')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_organization_id'))

    op.drop_table('uploaded_files')
    with op.batch_alter_table('sku_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_metrics_sku'))
        batch_op.drop_index(batch_op.f('ix_sku_metrics_organization_id'))
        batch_op.drop_index('idx_org_sku_metric_unique')

    op.drop_table('sku_metrics')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_organization_id'))
        batch_op.drop_index('idx_org_sku_unique')

    op.drop_table('products')
    with op.batch_alter_table('organization_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_subscriptions_organization_id'))

    op.drop_table('organization_subscriptions')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_organization_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('calculation_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_configs_organization_id'))

    op.drop_table('calculation_configs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_audit_org_action')
        batch_op.drop_index('idx_audit_created_at')

    op.drop_table('audit_logs')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index('idx_reset_token_user_expires')

    op.drop_table('password_reset_tokens')
    op.drop_table('organizations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
